---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
jenkins_version: "2.332.4"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_prefer_lts: false

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

# Plugin list can use the plugin name, or a name/version dict.
jenkins_plugins: 
 - ansicolor
 - ec2-plugin
 - aws-java-sdk-minimal
 - Ant
 - apache-httpcomponents-client-4-api
 - basic-branch-build-strategies
 - bootstrap4-api
 - bouncycastle-api
 - branch-api
 - build-timeout
 - checks-api
 - aws-credentials
 - command-launcher
 - configuration-as-code
 - credentials
 - credentials-binding
 - display-url-api
 - durable-task
 - echarts-api
 - email-ext
 - cloudbees-folder
 - font-awesome-api
 - git
 - git-client
 - git-server
 - github
 - github-api
 - github-branch-source
 - gradle
 - jackson2-api
 - jjwt-api
 - ace-editor
 - handlebars
 - momentjs
 - jaxb
 - jquery3-api
 - jsch
 - junit
 - ldap
 - lockable-resources
 - mailer
 - matrix-auth
 - matrix-project
 - node-iterator-api
 - okhttp-api
 - jdk-tool
 - antisamy-markup-formatter
 - pam-auth
 - workflow-aggregator
 - pipeline-graph-analysis
 - pipeline-utility-steps
 - workflow-api
 - pipeline-aws
 - workflow-basic-steps
 - pipeline-build-step
 - pipeline-model-definition
 - pipeline-model-extensions
 - pipeline-github-lib
 - workflow-cps
 - pipeline-input-step
 - workflow-job
 - pipeline-milestone-step
 - pipeline-model-api
 - workflow-multibranch
 - workflow-durable-task-step
 - pipeline-rest-api
 - workflow-scm-step
 - workflow-cps-global-lib
 - pipeline-stage-step
 - pipeline-stage-tags-metadata
 - pipeline-stage-view
 - workflow-step-api
 - workflow-support
 - plain-credentials
 - plugin-util-api
 - popper-api
 - resource-disposer
 - scm-api
 - script-security
 - snakeyaml-api
 - ssh-slaves
 - ssh-credentials
 - sshd
 - structs
 - timestamper
 - token-macro
 - trilead-api
 - variant
 - ws-cleanup
 
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

# If Jenkins is behind a proxy, configure this.
jenkins_proxy_host: ""
jenkins_proxy_port: ""
jenkins_proxy_noproxy:
  - "127.0.0.1"
  - "localhost"
